
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author martin
 */
public class Calificaciones extends javax.swing.JFrame {

    Ordenamiento or = new Ordenamiento();
    double[] calificaciones;
    int i;
    Ordenamiento o = new Ordenamiento();

    /**
     * Creates new form Calificaciones
     */
    public Calificaciones() {
        initComponents();
        this.setLocationRelativeTo(null);
        btnBuscar.setVisible(false);
        lblCa.setVisible(false);
        txtCali.setVisible(false);
        btnMostrar.setVisible(false);
        txaCalif.setVisible(false);
        txaCalif.setEditable(false);
        btnOrdenar.setVisible(false);
        btnBuscar.setVisible(false);
        btnAgregar.setVisible(false);
        txtCalificacion.setVisible(false);
        lblC.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNcali = new javax.swing.JLabel();
        txtNcali = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txtCalificacion = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        lblC = new javax.swing.JLabel();
        lblCa = new javax.swing.JLabel();
        txtCali = new javax.swing.JTextField();
        btnMostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaCalif = new javax.swing.JTextArea();
        btnOrdenar = new javax.swing.JButton();
        btnNcali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNcali.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNcali.setText("Numero de calificaciones");
        getContentPane().add(lblNcali, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        txtNcali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNcaliActionPerformed(evt);
            }
        });
        getContentPane().add(txtNcali, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 200, -1));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresar.png"))); // NOI18N
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 70, 40));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir peque.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 50, 60));

        txtCalificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCalificacionActionPerformed(evt);
            }
        });
        getContentPane().add(txtCalificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 200, -1));

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, -1, -1));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gatito.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 60, -1));

        lblC.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lblC.setText("Calificaciones");
        getContentPane().add(lblC, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        lblCa.setText("Calificacion");
        getContentPane().add(lblCa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));
        getContentPane().add(txtCali, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 200, -1));

        btnMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ver.png"))); // NOI18N
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 50, 40));

        txaCalif.setColumns(20);
        txaCalif.setRows(5);
        jScrollPane1.setViewportView(txaCalif);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 70, -1, 420));

        btnOrdenar.setText("Ordenar");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });
        getContentPane().add(btnOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, -1, -1));

        btnNcali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        btnNcali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNcaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnNcali, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Inicio ini = new Inicio();
        ini.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtCalificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCalificacionActionPerformed

    }//GEN-LAST:event_txtCalificacionActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        double c = Double.parseDouble(txtCalificacion.getText());
        if (c <= 10 && c >= 0) {
            try {
                calificaciones[i] = c;
                txtCalificacion.setText(null);
                i++;
                if (i < calificaciones.length) {
                    JOptionPane.showMessageDialog(null, "Ingrese la calificacion " + (i + 1));
                } else {
                    btnAgregar.setVisible(false);
                    txtCalificacion.setVisible(false);
                    lblC.setVisible(false);
                    btnRegresar.setVisible(true);
                    btnMostrar.setVisible(true);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Introduzca un numero");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Introduzca un numero entre 0 y 10");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        String t = null;
        for (int j = 0; j < (calificaciones.length); j++) {
            t = t + "\n" + calificaciones[j];
        }
        String tt = t.substring(5);
        txaCalif.setVisible(true);
        txaCalif.setText(tt);
        btnOrdenar.setVisible(true);
        btnMostrar.setVisible(false);
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        o.insertionSort(calificaciones);
        String t = null;
        for (int j = 0; j < calificaciones.length; j++) {
            t = t + "\n" + calificaciones[j];
        }
        String tt = t.substring(5);
        txaCalif.setText(tt);
        txaCalif.setVisible(true);
        btnOrdenar.setVisible(false);
        btnBuscar.setVisible(true);
        lblCa.setVisible(true);
        txtCali.setVisible(true);
    }//GEN-LAST:event_btnOrdenarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            double c = Double.parseDouble(txtCali.getText());
            double r = o.busquedaBin(calificaciones, c);
            if (r != -1) {
                JOptionPane.showMessageDialog(null, "Esa calificacion existe");
            } else {
                JOptionPane.showMessageDialog(null, "Esa calificacion no existe");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Introduzca el numero que quiera buscar");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNcaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNcaliActionPerformed
        try{
            int nCali = Integer.parseInt(txtNcali.getText());
        calificaciones = new double[nCali];
        txtCalificacion.setVisible(true);
        lblC.setVisible(true);
        txtNcali.setVisible(false);
        lblNcali.setVisible(false);
        btnAgregar.setVisible(true);
        btnNcali.setVisible(false);
        JOptionPane.showMessageDialog(null, "Ingrese la calificacion 1");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Introduzca un numero valido");
        }
    }//GEN-LAST:event_btnNcaliActionPerformed

    private void txtNcaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNcaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNcaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnNcali;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblCa;
    private javax.swing.JLabel lblNcali;
    private javax.swing.JTextArea txaCalif;
    private javax.swing.JTextField txtCali;
    private javax.swing.JTextField txtCalificacion;
    private javax.swing.JTextField txtNcali;
    // End of variables declaration//GEN-END:variables
}
