
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author martin
 */
public class Notas extends javax.swing.JFrame {

    Lista<String> q = new Lista();

    /**
     * Creates new form Notas
     */
    //DefaultListModel modeloLista;
    public Notas() {
        initComponents();
        this.setLocationRelativeTo(null);
        txaTexto.setVisible(false);
        btnGuardar.setVisible(false);
        btnBorrar.setVisible(false);
        btnBuscar.setVisible(false);
        txtTitulo.setVisible(false);
        lblTitulo.setVisible(false);
        txaP.setEditable(false);
        File file = new File("C:\\Users\\martin\\Documents\\NetBeansProjects\\Damasa\\notas\\notas.txt");
        if (file.exists()) {
            try {
                FileReader fileR = new FileReader("C:\\Users\\martin\\Documents\\NetBeansProjects\\Damasa\\notas\\notas.txt");
                BufferedReader debR = new BufferedReader(fileR);
                String linea;
                int i = 0;
                while ((linea = debR.readLine()) != null) {
                    if (i == 0) {
                        q.addBegin(new Nodo(linea));
                        i++;
                    } else {
                        q.add(new Nodo(linea));
                        i++;
                    }
                }

                fileR.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Notas.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Notas.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(Notas.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(q.size()!=0)
            txaP.setText(q.print2());

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaP = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaTexto = new javax.swing.JTextArea();
        btnGuardar = new javax.swing.JButton();
        txtTitulo = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        btnBorrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        rbtnAgregar = new javax.swing.JRadioButtonMenuItem();
        rbtnBorrar = new javax.swing.JRadioButtonMenuItem();
        rbtnBuscar = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir peque.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 50, 50));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresar.png"))); // NOI18N
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 80, 40));

        txaP.setColumns(20);
        txaP.setRows(5);
        jScrollPane3.setViewportView(txaP);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 60, 130, 520));

        txaTexto.setColumns(20);
        txaTexto.setRows(5);
        jScrollPane1.setViewportView(txaTexto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 770, 520));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 50, -1));
        getContentPane().add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 190, -1));

        lblTitulo.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblTitulo.setText("Titulo");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 100, 40));

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Borrar.png"))); // NOI18N
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 50, 40));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gatito.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 50, 40));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu.png"))); // NOI18N

        rbtnAgregar.setSelected(true);
        rbtnAgregar.setText("Agregar");
        rbtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAgregarActionPerformed(evt);
            }
        });
        jMenu1.add(rbtnAgregar);

        rbtnBorrar.setSelected(true);
        rbtnBorrar.setText("Borrar");
        rbtnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnBorrarActionPerformed(evt);
            }
        });
        jMenu1.add(rbtnBorrar);

        rbtnBuscar.setSelected(true);
        rbtnBuscar.setText("Buscar");
        rbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnBuscarActionPerformed(evt);
            }
        });
        jMenu1.add(rbtnBuscar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Inicio ini = new Inicio();
        ini.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        q.add(new Nodo(txtTitulo.getText()));

        String u = txtTitulo.getText();
        String n = txaTexto.getText();
        FileWriter flwr = null;
        BufferedWriter bfwr = null;
        File file = new File("C:\\Users\\martin\\Documents\\NetBeansProjects\\Damasa\\notas\\notas.txt");
        try {
            ObjectOutputStream guar = new ObjectOutputStream(new FileOutputStream(u));
            guar.writeObject(u);
            guar.writeObject(n);
            flwr = new FileWriter("C:\\Users\\martin\\Documents\\NetBeansProjects\\Damasa\\notas\\notas.txt");
            bfwr = new BufferedWriter(flwr);
            for (int i = 0; i < q.size(); i++) {
                bfwr.write(q.getAt(i));
                bfwr.newLine();
            }
            bfwr.close();
            guar.close();
            JOptionPane.showMessageDialog(null, "Se ha guardado la nota con exito");

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No se ha guardado la nota");
            Logger.getLogger(Notas.class.getName()).log(Level.SEVERE, null, ex);
        }
        txaTexto.setText(null);
        txtTitulo.setText(null);
        txtTitulo.setVisible(false);
        txaTexto.setVisible(false);
        btnGuardar.setVisible(false);
        txaP.setText(q.print2());
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void rbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnBuscarActionPerformed
        btnBuscar.setVisible(true);
        btnBorrar.setVisible(false);
        btnGuardar.setVisible(false);
        txtTitulo.setVisible(true);
        lblTitulo.setVisible(true);
    }//GEN-LAST:event_rbtnBuscarActionPerformed

    private void rbtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnBorrarActionPerformed
        btnBorrar.setVisible(true);
        btnBuscar.setVisible(false);
        btnGuardar.setVisible(false);
        txaTexto.setVisible(false);
        txtTitulo.setVisible(true);
        lblTitulo.setVisible(true);
    }//GEN-LAST:event_rbtnBorrarActionPerformed

    private void rbtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAgregarActionPerformed
        btnGuardar.setVisible(true);
        txaTexto.setVisible(true);
        btnBorrar.setVisible(false);
        btnBuscar.setVisible(false);
        txtTitulo.setVisible(true);
        lblTitulo.setVisible(true);
    }//GEN-LAST:event_rbtnAgregarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        String tit = txtTitulo.getText();
        File file = new File("C:\\Users\\martin\\Documents\\NetBeansProjects\\Damasa\\" + tit);
        boolean borrar = false;
        try {
            ObjectInputStream ent = new ObjectInputStream(new FileInputStream(tit));

            Object u = ent.readObject();

            if (tit.equals(u)) {
                ent.close();//tienes que cerrar el archivo para borrarlo
                if (file.delete()) {
                    btnBorrar.setVisible(false);
                    JOptionPane.showMessageDialog(null, "Se ha borrado la nota con exito");
                    borrar = true;
                    txtTitulo.setVisible(false);
                }
            } else {
                JOptionPane.showMessageDialog(null, "No existe nota con ese titulo");
            }
            ent.close();
        } catch (IOException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "No existe nota con ese titulo");
        }
        if(borrar){
            try {
                FileReader fileR = new FileReader("C:\\Users\\martin\\Documents\\NetBeansProjects\\Damasa\\notas\\notas.txt");
                BufferedReader debR = new BufferedReader(fileR);
                String linea;
                int i = 0;
                while ((linea = debR.readLine()) != null) {
                    if (linea.equals(tit)) {
                        q.deleteAt(i);
                        break;
                    } else {
                        i++;
                    }
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Notas.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Notas.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(Notas.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            try {
            FileWriter flwr = new FileWriter("C:\\Users\\martin\\Documents\\NetBeansProjects\\Damasa\\notas\\notas.txt");
            BufferedWriter bfwr = new BufferedWriter(flwr);
            for (int i = 0; i < q.size(); i++) {
                bfwr.write(q.getAt(i));
                bfwr.newLine();
            }
            bfwr.close();

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No se ha guardado la nota");
            Logger.getLogger(Notas.class.getName()).log(Level.SEVERE, null, ex);
        }
            if(q.size()!=0)
            txaP.setText(q.print2());
            else
                txaP.setText(null);
        }
        txtTitulo.setText(null);
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String titu = txtTitulo.getText();
        try {
            ObjectInputStream ent = new ObjectInputStream(new FileInputStream(titu));

            Object u = ent.readObject();
            Object n = ent.readObject();

            if (titu.equals(u)) {
                txaTexto.setVisible(true);
                txaTexto.setText((String) n);
                ent.close();
                JOptionPane.showMessageDialog(null, "Nota encontrado con exito");
            } else {
                JOptionPane.showMessageDialog(null, "No existe nota con ese titulo");
            }
        } catch (IOException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "No existe nota con ese titulo");
        }
        btnBuscar.setVisible(false);
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButtonMenuItem rbtnAgregar;
    private javax.swing.JRadioButtonMenuItem rbtnBorrar;
    private javax.swing.JRadioButtonMenuItem rbtnBuscar;
    private javax.swing.JTextArea txaP;
    private javax.swing.JTextArea txaTexto;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
